
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moxa
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jSeparator1 = new javax.swing.JSeparator();
        sbtnfirstname = new javax.swing.JButton();
        sbtnlastname = new javax.swing.JButton();
        sbtnusername = new javax.swing.JButton();
        sbtngender = new javax.swing.JButton();
        sbtndob = new javax.swing.JButton();
        sbtnpost = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stxtsearch = new javax.swing.JTextField();
        stxtfname = new javax.swing.JTextField();
        stxtuname = new javax.swing.JTextField();
        stxtlname = new javax.swing.JTextField();
        stxtgender = new javax.swing.JTextField();
        stxtdob = new javax.swing.JTextField();
        stxtpost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sbtnfirstname.setText("firstname");
        sbtnfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnfirstnameActionPerformed(evt);
            }
        });

        sbtnlastname.setText("lastname");
        sbtnlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnlastnameActionPerformed(evt);
            }
        });

        sbtnusername.setText("username");
        sbtnusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnusernameActionPerformed(evt);
            }
        });

        sbtngender.setText("gender");
        sbtngender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtngenderActionPerformed(evt);
            }
        });

        sbtndob.setText("Date of Birth");
        sbtndob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtndobActionPerformed(evt);
            }
        });

        sbtnpost.setText("post");
        sbtnpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnpostActionPerformed(evt);
            }
        });

        jLabel1.setText("Search:");

        stxtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtsearchActionPerformed(evt);
            }
        });

        stxtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtunameActionPerformed(evt);
            }
        });

        stxtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtlnameActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sbtnfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stxtfname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stxtuname)
                            .addComponent(sbtnusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sbtnlastname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stxtlname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stxtsearch)
                        .addGap(57, 57, 57))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(sbtnpost, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(stxtpost, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stxtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sbtngender, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sbtndob)
                            .addComponent(stxtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(sbtndob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stxtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sbtnfirstname)
                            .addComponent(sbtnusername)
                            .addComponent(sbtnlastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stxtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stxtuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stxtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(sbtngender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stxtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(sbtnpost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stxtpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbtnusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnusernameActionPerformed
        try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select username from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                
                 if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null,sql);
                    stxtuname.setText(rs.getString("username"));
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"notfound");
                   
                }

       
       }
       }
                catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_sbtnusernameActionPerformed

    private void sbtndobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtndobActionPerformed
       try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select dob from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                
                 if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null,sql);
                    stxtdob.setText(rs.getString("dob"));
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"notfound");
                   
                }

       
       }
       }
                catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_sbtndobActionPerformed

    private void stxtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtsearchActionPerformed
                try{  Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select * from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Record found");
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Record not found");

                }
            }
        }

        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }


    }//GEN-LAST:event_stxtsearchActionPerformed

    private void sbtnfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnfirstnameActionPerformed
       try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select firstname from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                
                 if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null,sql);
                    stxtfname.setText(rs.getString("firstname"));
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"notfound");
                   
                }

       
       }
       }
                catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_sbtnfirstnameActionPerformed

    private void sbtnlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnlastnameActionPerformed
try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select lastname from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                
                 if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null,sql);
                    stxtlname.setText(rs.getString("lastname"));
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"notfound");
                   
                }

       
       }
       }
                catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sbtnlastnameActionPerformed

    private void stxtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtlnameActionPerformed

    private void sbtngenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtngenderActionPerformed
     try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select gender from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                
                 if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null,sql);
                    stxtgender.setText(rs.getString("gender"));
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"notfound");
                   
                }

       
       }
       }
                catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_sbtngenderActionPerformed

    private void sbtnpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnpostActionPerformed
        try{Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-EKO9P440\\SQLEXPRESS:1433;databaseName=project;integratedSecurity=true;")){
                String sql = "select post from login  where username = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1,stxtsearch.getText());
                ResultSet rs = pst.executeQuery();
                
                 if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null,sql);
                    stxtpost.setText(rs.getString("post"));
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"notfound");
                   
                }

       
       }
       }
                catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_sbtnpostActionPerformed

    private void stxtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtunameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new app().setVisible(true);       
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton sbtndob;
    private javax.swing.JButton sbtnfirstname;
    private javax.swing.JButton sbtngender;
    private javax.swing.JButton sbtnlastname;
    private javax.swing.JButton sbtnpost;
    private javax.swing.JButton sbtnusername;
    private javax.swing.JTextField stxtdob;
    private javax.swing.JTextField stxtfname;
    private javax.swing.JTextField stxtgender;
    private javax.swing.JTextField stxtlname;
    private javax.swing.JTextField stxtpost;
    private javax.swing.JTextField stxtsearch;
    private javax.swing.JTextField stxtuname;
    // End of variables declaration//GEN-END:variables
}
